name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    strategy:
      matrix:
        include:
          - name: amd64
            target: x86_64-unknown-linux-musl
            runs-on: ubuntu-24.04
          - name: arm64
            target: aarch64-unknown-linux-musl
            runs-on: ubuntu-24.04-arm

    runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: read
    #   packages: write # Required for pushing to GitHub Packages Registry (ghcr.io)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/${{ matrix.name }}

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: docker.io
          # For ghcr.io, registry is ghcr.io. For Docker Hub, you can omit this or use docker.io
          # registry: ghcr.io # Uncomment and set if not Docker Hub

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/${{ matrix.name }}
          build-args: |
            RUST_TARGET=${{ matrix.target }}
          push: true
          tags: |
            ${{ vars.DOCKER_REGISTRY_TARGET }}:latest
            ${{ vars.DOCKER_REGISTRY_TARGET }}:${{ github.sha }}
          # Add labels if needed
          # labels: |
          #   org.opencontainers.image.source=${{ github.repositoryUrl }}
          #   org.opencontainers.image.revision=${{ github.sha }}
