name: Docker Build and Push

on:
  push:
    branches:
      - main
      - build_action # temporary to test builds now.

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    #   packages: write # Required for pushing to GitHub Packages Registry (ghcr.io)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: docker.io
          # For ghcr.io, registry is ghcr.io. For Docker Hub, you can omit this or use docker.io
          # registry: ghcr.io # Uncomment and set if not Docker Hub

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ vars.DOCKER_REGISTRY_TARGET }}:latest
            ${{ vars.DOCKER_REGISTRY_TARGET }}:${{ github.sha }}
          # Add build arguments if needed
          # build-args: |
          #   ARG_NAME=value
          # Add labels if needed
          # labels: |
          #   org.opencontainers.image.source=${{ github.repositoryUrl }}
          #   org.opencontainers.image.revision=${{ github.sha }}
